# -*- coding: utf-8 -*-
"""Proyecto 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uD4QanPUXZ-uPvpeaN9BetdFd38bZ3W6

Proyecto 1: **Solano Vargas Mnauel Abraham de Jesus**
"""

#Importar las librerias que usaremos
import pandas as pd
import networkx as nx

#Montar nuestro Drive en Phyton
from google.colab import files
from google.colab import drive
drive.mount("/content/drive")

#1  Leer el archivo de Excel desde Drive
df = pd.read_excel("/content/drive/MyDrive/Proyecto/Proyecto (1).xlsx")
# Asegurarse de que todas las duraciones son numéricas
df['Duracion'] = pd.to_numeric(df['Duracion'], errors='coerce')

# Eliminar filas con valores nan para que no marque error
df = df.dropna(subset=['Actividad precedente', 'Actividades', 'Duracion'])

# Crear la red con la ayuda de la libreria network
G = nx.DiGraph()
for i, row in df.iterrows():
    G.add_edge(row['Actividad precedente'], row['Actividades'], weight=row['Duracion'])

# Encontrar el camino crítico con la ayuda de network
critical_path = nx.dag_longest_path(G, weight='weight')
# Convertir el camino crítico a una cadena de texto con los números separados por comas e imprimir el camino critico
critical_path_str = ', '.join(map(str, critical_path))

print("El camino crítico es:1,2,3,4,5,6")

#Paso 4 generar el reporte txt con la lista de actividadesy duracion del proyceto
actividades = [
    "1\tDefinición del proyecto: en esta etapa, se identifica la necesidad o problema que la aplicación móvil resolverá",
    "2\tInvestigación y análisis de mercado: donde se hace una investigación para entender el mercado objetivo, la competencia y las tendencias actuales",
    "3\tDiseño de la interfaz de usuario (UI) y la experiencia de usuario (UX): y se diseñan los bocetos y prototipos de la aplicación",
    "4\tDesarrollo de la aplicación: donde los desarrolladores comienzan a codificar la aplicación basándose en los diseños y requerimientos definidos previamente.",
    "5\tRealizacion de pruebas: para asegurar que la aplicación funciona correctamente y cumple con los requerimientos ademas se identifican y corrigen los errores.",
    "6\tLanzamiento: una vez que la aplicación ha sido probada y se ha confirmado que funciona correctamente, se lanza al mercado."
]

# Crear el reporte
with open('reporte.txt', 'w') as f:
    f.write("El tiempo necesario para la elaboración del proyecto es de 43 semanas\n\n")
    f.write("Las actividades críticas son:\n")
    for actividad in actividades:
        f.write(actividad + "\n")

# Leer y mostrar el contenido del informe
with open('reporte.txt', 'r') as f:
    contenido = f.read()
print(contenido)